services:
  app:
    container_name: api_nestjs_boilerplate
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    command: pnpm start:dev
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: db_nestjs_boilerplate
    restart: always
    environment:
      PGPORT: ${DB_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    expose:
      - ${DB_PORT}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
