name: Codecov

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3.6.0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 22.14.0

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        id: pnpm-install
        with:
          version: 10.10.0
          run_install: false

      - name: Install dependencies
        run: pnpm i --no-frozen-lockfile

      - name: Test
        run: pnpm test

      - name: Codecov
        uses: codecov/codecov-action@v5
