name: ERD Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-erd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.15.0

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        id: pnpm-install
        with:
          version: 9.15.9
          run_install: false

      - name: Generate ERD Diagrams
        run: pnpm build:database-docs
